CREATE TABLE `T_BOARD` (
  `BOARD_SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(100) NOT NULL,
  `CONTENTS` text NOT NULL,
  `REG_DATE` datetime NOT NULL,
  PRIMARY KEY (`BOARD_SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8 COMMENT='게시판';

-- 샘플 INSERT QUERY
INSERT INTO T_BOARD (TITLE,CONTENTS,REG_DATE) VALUES
  ('테스트','테스트 컨텐츠','2020-10-06 23:17:38.0');