CREATE TABLE `T_BOARD` (
  `BOARD_SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(100) NOT NULL,
  `CONTENTS` text NOT NULL,
  `REG_DATE` datetime NOT NULL,
  PRIMARY KEY (`BOARD_SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8 COMMENT='게시판';

-- 샘플 INSERT QUERY
INSERT INTO T_BOARD (TITLE,CONTENTS,REG_DATE) VALUES
  ('테스트','테스트 컨텐츠','2020-10-06 23:17:38.0');

-- enum 클래스 활용을 위한 컬럼 추가
ALTER TABLE `T_BOARD`
	CHANGE COLUMN `BOARD_SEQ` `BOARD_SEQ` INT(11) NOT NULL AUTO_INCREMENT COMMENT '게시물 번호' FIRST,
	ADD COLUMN `BOARD_TYPE` VARCHAR(10) NOT NULL COMMENT '게시판 종류' AFTER `BOARD_SEQ`
	;


-- 테이블 생성 쿼리
CREATE TABLE `T_UPLOAD_FILE` (
`UPLOAD_FILE_SEQ` INT(11) NOT NULL AUTO_INCREMENT COMMENT '파일 고유번호',
`PATHNAME` VARCHAR(100) NOT NULL COMMENT '전체경로' COLLATE 'utf8_general_ci',
`FILENAME` VARCHAR(50) NOT NULL COMMENT '파일명' COLLATE 'utf8_general_ci',
`ORIGINAL_FILENAME` VARCHAR(100) NOT NULL COMMENT '원본 파일명' COLLATE 'utf8_general_ci', `SIZE` INT(11) NOT NULL COMMENT '파일크기',
`CONTENT_TYPE` VARCHAR(50) NOT NULL COMMENT '컨텐츠 종류' COLLATE 'utf8_general_ci',
`RESOURCE_PATHNAME` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '리소스 파일경로' COLLATE 'utf8_general_ci',
`REG_DATE` DATETIME NOT NULL COMMENT '등록일자', PRIMARY KEY (`UPLOAD_FILE_SEQ`) USING BTREE
) COMMENT='파일' COLLATE='utf8_general_ci' ENGINE=InnoDB AUTO_INCREMENT=4 ;