CREATE TABLE `T_BOARD` (
  `BOARD_SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(100) NOT NULL,
  `CONTENTS` text NOT NULL,
  `REG_DATE` datetime NOT NULL,
  PRIMARY KEY (`BOARD_SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8 COMMENT='게시판';

-- 샘플 INSERT QUERY
INSERT INTO T_BOARD (TITLE,CONTENTS,REG_DATE) VALUES
  ('테스트','테스트 컨텐츠','2020-10-06 23:17:38.0');

-- enum 클래스 활용을 위한 컬럼 추가
ALTER TABLE `T_BOARD`
	CHANGE COLUMN `BOARD_SEQ` `BOARD_SEQ` INT(11) NOT NULL AUTO_INCREMENT COMMENT '게시물 번호' FIRST,
	ADD COLUMN `BOARD_TYPE` VARCHAR(10) NOT NULL COMMENT '게시판 종류' AFTER `BOARD_SEQ`
	;